#!/usr/bin/sh

# General Settings
bspc config border_width         2
bspc config window_gap           5
bspc config left_padding         5
bspc config top_padding         29
bspc config bottom_padding       5
bspc config right_padding        5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color    "#4C566A"
bspc config active_border_color    "#1E1E1E"
bspc config focused_border_color   "#FFFFFF"
bspc config presel_feedback_color  "#5E81AC"
bspc config urgent_border_color    "#DD2727"

bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen enter

# Mouse Controls
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner

# Launch startup applications
startup_script

# Moniters
isMonitorConnected -1 && bspc monitor "${PRIMARY_MONITOR%%:*}"   -d 0 1 2 3 4 5 6 7 8 9
isMonitorConnected -2 && bspc monitor "${SECONDARY_MONITOR%%:*}" -d 0 1 2 3 4 5 6 7 8 9
isMonitorConnected -3 && bspc monitor "${TERTIARY_MONITOR%%:*}"  -d 0 1 2 3 4 5 6 7 8 9

# Window Rules
bspc rule -r "*"

scratchpad_offset='468+208'
bspc rule -a 'Scratchpad:*' sticky=on
bspc rule -a 'Scratchpad:*' state=floating
bspc rule -a 'Scratchpad:*' locked=on
bspc rule -a 'Scratchpad:primary' monitor="${PRIMARY_MONITOR%%:*}"
bspc rule -a 'Scratchpad:primary' rectangle=980x660+"$(addxy "$(getMonitorPosition -1)" "$scratchpad_offset")"
bspc rule -a 'Scratchpad:secondary' monitor="${SECONDARY_MONITOR%%:*}"
bspc rule -a 'Scratchpad:secondary' rectangle=980x660+"$(addxy "$(getMonitorPosition -2)" "$scratchpad_offset")"
bspc rule -a 'Scratchpad:tertiary' monitor="${TERTIARY_MONITOR%%:*}"
bspc rule -a 'Scratchpad:secondary' rectangle=980x660+"$(addxy "$(getMonitorPosition -2)" "$scratchpad_offset")"

bspc rule -a 'Brave-browser' desktop='^1'
bspc rule -a 'Brave-browser' locked=on
bspc rule -a 'Brave-browser' focus=on

bspc rule -a 'Brave-browser-beta' desktop='^1'
bspc rule -a 'Brave-browser-beta' locked=on
bspc rule -a 'Brave-browser-beta' focus=on

bspc rule -a 'Gimp' focus=off
bspc rule -a 'Gimp' follow=off

bspc rule -a 'Zathura' state=tiled

bspc rule -a 'qBittorrent' state=floating

bspc rule -a 'Pavucontrol' state=floating
bspc rule -a 'Pavucontrol' rectangle=906x425+1000+20

bspc rule -a 'Volctl:volctl:Preferences' state=floating
bspc rule -a 'Volctl:volctl:Preferences' rectangle=421x357+1485+20

bspc rule -a 'Zotero:*' state=floating

bspc rule -a 'VirtualBoxVM' state=floating
bspc rule -a 'VirtualBoxVM' desktop='^10'

bspc rule -a 'YouTube Music' state=floating

## Allow bspwm to Swallow
#pidof bspswallow || bspswallow &

# Default Desktop
bspc desktop -f focused:'^2'
