#! /bin/sh

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

# General Settings
bspc config border_width         1
bspc config window_gap           5
bspc config left_padding         5
bspc config top_padding         19
bspc config bottom_padding       5
bspc config right_padding        5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color	   "#4c566a"
bspc config active_border_color    "#1e1e1e"
bspc config focused_border_color   "#FF0000"
bspc config presel_feedback_color  "#5e81ac"
bspc config urgent_border_color    "#dd2727"

bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen enter

# Window Rules
bspc rule -r "*"

bspc rule -a scratchpad sticky=on
bspc rule -a scratchpad state=floating
bspc rule -a scratchpad hidden=on
bspc rule -a scratchpad locked=on

bspc rule -a Brave-browser desktop='^1'
bspc rule -a Brave-browser locked=on
bspc rule -a Brave-browser focus=on
bspc rule -a Brave-browser follow=off
bspc rule -a Brave-browser border=on

bspc rule -a Gimp focus=off
bspc rule -a Gimp follow=off

bspc rule -a Zathura state=tiled

# Default Desktop
bspc desktop -f focused:'^2'
