#! /bin/sh

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           2
bspc config left_padding         5
bspc config top_padding          5
bspc config bottom_padding       5
bspc config right_padding        5

bspc config split_ratio          0.501
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen enter

bspc config normal_border_color	   "#4c566a"
bspc config active_border_color    "#1e1e1e"
bspc config focused_border_color   "#FFFFFF"
bspc config presel_feedback_color  "#5e81ac"
bspc config urgent_border_color    "#dd2727"

# Mouse Controls
bspc config pointer_modifier control
bspc config pointer_action1 move
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner

bspc rule -r "*"

bspc rule -a scratchpad:main sticky=on
bspc rule -a scratchpad:main state=floating
bspc rule -a scratchpad:main hidden=on
bspc rule -a scratchpad:main locked=on

bspc rule -a Brave-browser desktop='^1'
bspc rule -a Brave-browser locked=on
bspc rule -a Brave-browser focus=on

bspc rule -a Gimp focus=off
bspc rule -a Gimp follow=off

bspc rule -a Zathura state=tiled

# Allow bspwm to Swallow
pidof bspswallow || bspswallow &

# Have bspwm start focused on the default desktop
bspc desktop -f focused:'^2'
